---
# Make directories according to inventory file and cleanup last config
  - name: Make directories cleanup
    hosts: leafs, spines
    tasks:
    - name: Register variables underlay
      include_vars:
        file: "{{ lookup('env','PWD') }}/vars/underlay.yml"
        name: underlay
    - name: Create config directory
      file:
        path: "{{ lookup('env','PWD')}}/configs/{{ inventory_hostname }}"
        state: directory
    - name: Delete old config file (if exists)
      file:
        path: "{{ lookup('env','PWD') }}/configs/{{ inventory_hostname }}/{{ inventory_hostname }}_final.cfg"
        state: absent
    - name: Create Interface config
      template: 
        src: "{{ lookup('env','PWD') }}/templates/underlay.j2"
        dest: "{{ lookup('env','PWD') }}/configs/{{ inventory_hostname }}/{{ inventory_hostname }}_underlay.cfg"  
 
  - name: Create spine configurations for underlay
    hosts: spines
    tasks: 
    - name: Register variables (underlay)
      include_vars:
        file: "{{lookup('env','PWD')}}/vars/underlay.yml"
        name: underlay
    - name: Register variables (underlay)
      include_vars:
        file: "{{lookup('env','PWD')}}/vars/overlay.yml"
        name: overlay
    - name: Create Spine EVPN Underlay config
      template: 
        src: "{{lookup('env','PWD')}}/templates/overlay_spine.j2"
        dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}/{{inventory_hostname}}_overlay.cfg"

  - name: Create leaf configurations for underlay and VXLAN tenants
    hosts: leafs
    tasks: 
    - name: Register variables (underlay)
      include_vars:
        file: "{{lookup('env','PWD')}}/vars/underlay.yml"
        name: underlay
    - name: Register variables (underlay)
      include_vars:
        file: "{{lookup('env','PWD')}}/vars/overlay.yml"
        name: overlay
    - name: Register VXLAN variables
      include_vars:
        file: "{{lookup('env','PWD')}}/vars/VXLAN.yml"
        name: VXLAN
    - name: Create Leaf EVPN Underlay config
      template: 
        src: "{{lookup('env','PWD')}}/templates/overlay_leaf.j2"
        dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}/{{inventory_hostname}}_overlay.cfg"   
    - name: Create VXLAN Configuration
      template: 
        src: "{{lookup('env','PWD')}}/templates/VXLAN.j2"
        dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}/{{inventory_hostname}}_VXLAN.cfg"
